binarytree: binarytree.o main_binarytree.o

binarytree_mirror: binarytree_mirror.o main_binarytree_mirror.o binarytree.o

binarysearchtree: binarysearchtree.o main_binarysearchtree.o

bst_advanced: bst_advanced.o main_bst_advanced.o
