all: knapsack knapsackDP knapsackDP2 subsetSum

knapsack: knapsack.o knapsackMain.o

knapsackDP: knapsackDP.o knapsackDPMain.o

knapsackDP2: knapsackDP2.o knapsackDP2Main.o

subsetSum: subsetSum.o subsetSumMain.o

clean:
